/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package resources.views.components;

import entities.order.OrderData;
import entities.route.RouteData;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import resources.controller.routes.RoutesCreate;
import resources.controller.routes.RoutesShow;
import entities.route.RouteData;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import resources.views.pages.OrderView;
import resources.views.components.RouteInputComponent;

/**
 *
 * @author Bravo
 */
public class RouteMenuComponent extends javax.swing.JPanel {
       
       protected JFrame frame;
    
    /**
     * Creates new form RouteMenuComponent
     */
    public RouteMenuComponent(JFrame frame) {
        this.frame = frame;
        initComponents();
        setDataRoutes();
        setDataOrder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addRoute = new javax.swing.JButton();
        editRoute = new javax.swing.JButton();
        delRoute = new javax.swing.JButton();
        orderRoute = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        exportOrder = new javax.swing.JButton();
        deptSearchField = new javax.swing.JTextField();
        destSearchField = new javax.swing.JTextField();
        searchRoute = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(227, 244, 244));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(512, 720));

        jPanel1.setBackground(getBackground());
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(512, 720));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Rute Tersedia");

        jScrollPane1.setBackground(jPanel1.getBackground());
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(512, 720));
        jScrollPane1.setViewportView(jTable1);

        jTable1.setBackground(new java.awt.Color(196, 223, 223));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Asal", "Tujuan", "Waktu", "Stok", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        addRoute.setBackground(new java.awt.Color(90, 219, 181));
        addRoute.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        addRoute.setText("Baru");
        addRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRouteActionPerformed(evt);
            }
        });

        editRoute.setBackground(new java.awt.Color(85, 194, 218));
        editRoute.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        editRoute.setText("Edit");
        editRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRouteActionPerformed(evt);
            }
        });

        delRoute.setBackground(new java.awt.Color(255, 0, 0));
        delRoute.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        delRoute.setText("Hapus");
        delRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delRouteActionPerformed(evt);
            }
        });

        orderRoute.setBackground(new java.awt.Color(90, 219, 181));
        orderRoute.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        orderRoute.setText("Pesan");
        orderRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderRouteActionPerformed(evt);
            }
        });

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1280, 720));

        jTable2.setBackground(jTable1.getBackground());
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode Pesanan", "Kode Rute", "Jumlah", "Total", "Status"
            }
        ));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jTabbedPane1.addTab("Transaksi", jScrollPane2);

        exportOrder.setBackground(new java.awt.Color(85, 194, 218));
        exportOrder.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        exportOrder.setText("Export");
        exportOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportOrderActionPerformed(evt);
            }
        });

        searchRoute.setBackground(new java.awt.Color(85, 194, 218));
        searchRoute.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        searchRoute.setText("Cari");
        searchRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRouteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Asal");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Tujuan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exportOrder)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addRoute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(orderRoute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editRoute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delRoute))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deptSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(destSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchRoute)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deptSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderRoute, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exportOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        deptSearchField.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                searchFieldChanged();
            }
            public void removeUpdate(DocumentEvent e) {
                searchFieldChanged();
            }
            public void insertUpdate(DocumentEvent e) {
                searchFieldChanged();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldChanged() {
        if(destSearchField.getText().equals("") && deptSearchField.getText().equals("")) {
            setDataRoutes();
        }
    }
    
    private void delRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delRouteActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        int id = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());
        new RoutesCreate().delete(id);
        setDataRoutes();
    }//GEN-LAST:event_delRouteActionPerformed

    private void addRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRouteActionPerformed
        // TODO add your handling code here:
        RouteInputComponent dialog = new RouteInputComponent(this.frame, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_addRouteActionPerformed

    private void orderRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderRouteActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        int id = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());
        OrderInputComponent dialog = new OrderInputComponent(this.frame, true, id);
        dialog.setVisible(true);
    }//GEN-LAST:event_orderRouteActionPerformed

    private void editRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRouteActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        int id = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());
        EditRouteComponent dialog = new EditRouteComponent(this.frame, true, new RoutesShow().show(id));
        dialog.setVisible(true);
    }//GEN-LAST:event_editRouteActionPerformed

    private void exportOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportOrderActionPerformed

    private void searchRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRouteActionPerformed
        // TODO add your handling code here:
//        System.out.println(destSearchField.getText().equals(""));
        if(destSearchField.getText().equals("") && deptSearchField.getText().equals("")) {
            setDataRoutes();
        } else if(!destSearchField.getText().equals("") && !deptSearchField.getText().equals("")) {
            setDataRoutes(deptSearchField.getText(), destSearchField.getText());
        }
    }//GEN-LAST:event_searchRouteActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRoute;
    private javax.swing.JButton delRoute;
    private javax.swing.JTextField deptSearchField;
    private javax.swing.JTextField destSearchField;
    private javax.swing.JButton editRoute;
    private javax.swing.JButton exportOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private static javax.swing.JTable jTable1;
    private static javax.swing.JTable jTable2;
    private javax.swing.JButton orderRoute;
    private javax.swing.JButton searchRoute;
    // End of variables declaration//GEN-END:variables
    
    public static void setDataRoutes() {
        ArrayList<RouteData> data = new RoutesShow().show();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        // Clear existing rows first
        model.setRowCount(0);

        for(RouteData d: data) {
            Object[] row = {
                d.id,           // Assuming getId() returns Integer for "No"
                d.departure,    // String for "Asal"
                d.destination,  // String for "Tujuan"
                d.dept_date,     // String for "Waktu"
                d.getStock(),        // Integer for "Stok"
                d.price         // Integer for "Harga"
            };
            model.addRow(row);
        }
    }
    
    public static void setDataRoutes(String dept, String dest) {
        ArrayList<RouteData> data = new RoutesShow().show(new RouteData(dept, dest));

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        // Clear existing rows first
        model.setRowCount(0);

        for(RouteData d: data) {
            Object[] row = {
                d.id,           // Assuming getId() returns Integer for "No"
                d.departure,    // String for "Asal"
                d.destination,  // String for "Tujuan"
                d.dept_date,     // String for "Waktu"
                d.getStock(),        // Integer for "Stok"
                d.price         // Integer for "Harga"
            };
            model.addRow(row);
        }
    }
    
    
    public static void setDataOrder() {
        ArrayList<OrderData> data = new resources.controller.order.OrderShow().show();

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
        // Clear existing rows first
        model.setRowCount(0);

        int i = 0;
        
        for(OrderData d: data) {
            Object[] row = {
                ++i,           // Assuming getId() returns Integer for "No"
                d.id,
                d.route_id,     // String for "Asal"
                d.amount,     // String for "Waktu"
                d.total,        // Integer for "Stok"
                d.status         // Integer for "Harga"
            };
            model.addRow(row);
        }
    }
}
